# Modified the makefile of an old DriftPointsCounter version, as I got
# no idea how to write one myself.

GPP = g++
GCC = gcc
RNPC_OUTFILE = "RNPC.so"

COMPILE_FLAGS = -m32 -fPIC -c -O3 -w -D LINUX -D PROJECT_NAME=\"RNPC\" -I ./SDK/amx/

RNPC = -D RNPC $(COMPILE_FLAGS)

all: RNPC

clean:
	-rm -f *~ *.o *.so

DriftPointsCounter: clean
	$(GPP) $(RNPC) ./SDK/amx/*.c
	$(GPP) $(RNPC) ./SDK/*.cpp
	$(GPP) $(RNPC) ./ThirdPartySource/*.cpp
	$(GPP) $(RNPC) *.cpp
	$(GPP) -m32 -O2 -fshort-wchar -shared -o $(RNPC_OUTFILE) *.o
